runamqp:
  build: .
  links:
    - rabbitmq
  volumes:
    - .:/go/src/github.com/mergermarket/run-amqp

sampleapp:
  build: sample
  links:
    - rabbitmq
  volumes:
    - .:/go/src/github.com/mergermarket/run-amqp
  ports:
    - "8080:8080"

rabbitmq:
  image: rabbitmq:3-management
  expose:
    - "5672"
    - "15672"
  ports:
    - "15672:15672"