name: tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: |
          ./scripts/docker-run-all-tests.sh
